### ISSUE TITLE
Sikke 

### ISSUE THREAD

**Issue by ozkann** [sikke-official/web-wallet#2]
Web de Beta surecindeki açilmis keser ile yeni keseler arası transfer yapilamiyor.

Birtakım sorunlar

1.Sikke mobil uygulamasindan sikke gönderim tarihi saati yanlış

**Comment by sikke-official** [comment]
MAINNET sürümünde bu sorun olmayacaktır. Eski keseler kullanılabilir haldeler.
Mobil sürüm güncellenecek...
